import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { TranscriptionProvider } from '@/context/TranscriptionContext';
import { StyleProvider } from '@/context/StyleContext';
import { SettingsButton } from '@/components/settings/SettingsButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleProvider>
          <TranscriptionProvider>
            {children}
            <Toaster />
            <div className="absolute bottom-4 right-4 z-50">
              <SettingsButton />
            </div>
          </TranscriptionProvider>
        </StyleProvider>
      </body>
    </html>
  );
}
